version: '3.8'

services:
  postgres.test:
    image: postgres:16
    container_name: postgres_test
    env_file:
      - .env.test.local
    ports:
      - '5433:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data:
#docker-compose -f docker-compose.test.yml up --build
