version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env.development.local
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nestjs-dockerfile:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports: ['3000:3000']
    env_file:
      - .env.development.local
    environment:
      - NODE_ENV=development
    volumes: ['./:/usr/src/app/src']

volumes:
  postgres_data:
